---
- name: Install Telnet and check SQL
  hosts: all
    
  tasks:
  
  - name: Check SQL Server is Installed
    win_service:
     name: MSSQLSERVER
    register: sqlstatus
  - name: Start SQL Service
    win_service:
     name: MSSQLSERVER
     start_mode: auto
     state: started
    when: sqlstatus.exists
 - name: Install IIS Web-Server with sub features and management tools
  ansible.windows.win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: Reboot if installing Web-Server feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required     
